export const ALL_POST_REQUEST = "ALL_POST_REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCTS_FAIL";
export const ALL_PRODUCT_ERRORS = "ALL_PRODUCT_ERRORS";
