import './globals.css'
import { Inter } from 'next/font/google';
import Footer from '@/components/common/Footer';
import { Providers } from './providers';
import Navigation from '@/components/common/Navbar';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} light`}>
        {/* <h3>Header</h3> */}
        <Providers>
          {/* <Navigation />
          {children}
          <Footer /> */}
          {children}
        </Providers>
      </body>
    </html>
  )
}
